# -*- coding: utf-8 -*-
"""XAAP manual trigger checker GUI."""

from __future__ import annotations

import argparse
import csv
import json
import logging
import os
import sys
from pathlib import Path
from typing import Iterable, List

import matplotlib.pyplot as plt
import numpy as np
import pyqtgraph as pg
from PyQt5.QtGui import QKeySequence
from PyQt5.QtWidgets import (
    QApplication,
    QComboBox,
    QPushButton,
    QShortcut,
    QSplitter,
    QVBoxLayout,
    QWidget,
)
from pyqtgraph import TableWidget
from pyqtgraph.Qt import QtCore, QtGui
from pyqtgraph.parametertree import Parameter, ParameterTree
from pyqtgraph.widgets.MatplotlibWidget import MatplotlibWidget

from xaap.configuration.xaap_configuration import configure_logging
from xaap.models import xaap_check

logger = logging.getLogger(__name__)

# Table configuration -----------------------------------------------------------------
TABLE_HEADERS: List[str] = [
    "Trigger code",
    "Cod Registro",
    "Volcan",
    "Estación",
    "Net",
    "Componente",
    "Fecha",
    "Hora",
    "Tipo",
    "S-P",
    "Coda",
    "Amp-Cuentas",
    "T",
    "f",
    "RMSXXXXXX",
    "Stream",
    "Status",
]

COLUMN_WIDTHS: List[int] = [
    0,   # Trigger code (kept hidden)
    100, # Cod Registro
    70,  # Volcan
    70,  # Estación
    40,  # Net
    100, # Componente
    80,  # Fecha
    65,  # Hora
    65,  # Tipo
    40,  # S-P
    50,  # Coda
    110, # Amp-Cuentas
    50,  # T
    50,  # f
    50,  # RMSXXXXXX
    50,  # Stream (button column)
    100, # Status (combo column)
]

# Columns from the prediction DataFrame that are projected into the table. Blank
# strings are kept because the CSV generated by the training step already relies on
# them. They are populated with empty values and later replaced with widgets.
DISPLAY_COLUMNS: List[str] = [
    "trigger_code",
    "",
    "",
    "Station",
    "Network",
    "Component",
    "Fecha",
    "Hora",
    "prediction",
    "",
    "coda",
    "",
    "",
    "",
    "",
    "",
    "",
]

BUTTON_COLUMN_INDEX = 15
STATUS_COLUMN_INDEX = 16
STATUS_OPTIONS: Iterable[str] = ("Exist", "Not Exist")
STATUS_DEFAULT_INDEX = 0
EXPORT_FILENAME = Path("./temp.csv")


class xaapCheck(QWidget):
    """Main widget that allows operators to review and correct trigger metadata."""

    def __init__(self, args: argparse.Namespace) -> None:
        """Initialise the widget and restore the stored configuration."""
        super().__init__()
        xaap_check.logger.info("Continuation of all this")

        self.xaap_check_json = args.xaap_check_config

        self.setup_gui()

        self.params = self.create_parameters()
        self.tree.setParameters(self.params, showTop=True)
        logger.info("Parameter tree populated.")

        self.classifications_path = Path(
            self.params.param("classification", "classification_folder").value()
        )
        if self.classifications_path.exists():
            classified_triggers_files = [
                os.path.splitext(path)[0]
                for path in os.listdir(self.classifications_path)
                if Path(self.classifications_path, path).is_file()
            ]
            self.params.param("classification", "classification_file").setLimits(
                classified_triggers_files
            )
        else:
            logger.warning(
                "Classification path '%s' does not exist.",
                self.classifications_path,
            )

        logger.info("Try to connect to a miniseed server")
        xaap_check.connect_to_mseed_server(self)

        self.configure_signals()

    # ------------------------------------------------------------------ GUI helpers --
    def setup_gui(self) -> None:
        """Build the Qt layout and plotting widgets."""
        layout = QVBoxLayout()
        layout.setContentsMargins(0, 0, 0, 0)
        self.setLayout(layout)
        self.layout = layout

        # Register keyboard shortcuts for common tasks.
        self.shortcuts: List[QShortcut] = []
        self._create_shortcut("Ctrl+Q", QApplication.instance().quit)
        self._create_shortcut("Ctrl+L", self.load_data_to_tbl_widget)
        self._create_shortcut("Ctrl+G", self.get_plots)
        self._create_shortcut("Ctrl+C", self.clear_all_plots)

        self.table_widget = TableWidget(editable=True)
        self._configure_table()

        self.tree = ParameterTree()
        self.datetime_axis_1 = pg.graphicsItems.DateAxisItem.DateAxisItem(
            orientation="bottom", utcOffset=5
        )
        self.datetime_axis_2 = pg.graphicsItems.DateAxisItem.DateAxisItem(
            orientation="bottom", utcOffset=5
        )

        # Main and side plotting areas.
        self.main_layout = pg.GraphicsLayoutWidget()
        self.side_layout = pg.GraphicsLayoutWidget()

        self.trigger_plot = self.main_layout.addPlot(
            row=0, col=0, axisItems={"bottom": self.datetime_axis_1}
        )
        self.paded_plot = self.main_layout.addPlot(
            row=1, col=0, axisItems={"bottom": self.datetime_axis_2}
        )

        # Enable rectangular zooming for time series plots.
        self.trigger_plot.getViewBox().setMouseMode(pg.ViewBox.RectMode)
        self.paded_plot.getViewBox().setMouseMode(pg.ViewBox.RectMode)

        self.mw = MatplotlibWidget()
        self.plot_frequency_spectrum = self.side_layout.addPlot(row=1, col=0)
        self.plot_frequency_spectrum.getViewBox().setMouseMode(pg.ViewBox.RectMode)

        # Arrange widgets using splitters: [Parameter tree | plots/table | spectrum].
        self.splitter_horizontal = QSplitter(QtCore.Qt.Orientation.Horizontal)
        self.splitter_vertical = QSplitter(QtCore.Qt.Orientation.Vertical)
        self.splitter_vertical_side = QSplitter(QtCore.Qt.Orientation.Vertical)

        self.splitter_vertical.addWidget(self.main_layout)
        self.splitter_vertical.addWidget(self.table_widget)

        self.splitter_vertical_side.addWidget(self.mw)
        self.splitter_vertical_side.addWidget(self.side_layout)

        self.splitter_horizontal.addWidget(self.tree)
        self.splitter_horizontal.addWidget(self.splitter_vertical)
        self.splitter_horizontal.addWidget(self.splitter_vertical_side)

        self.splitter_horizontal.setSizes([265, 635, 200])
        self.splitter_vertical.setSizes([600, 200])

        layout.addWidget(self.splitter_horizontal)

    def _create_shortcut(self, key_sequence: str, callback) -> None:
        """Register a keyboard shortcut and keep a reference to it."""
        shortcut = QShortcut(QKeySequence(key_sequence), self)
        shortcut.activated.connect(callback)  # type: ignore[arg-type]
        self.shortcuts.append(shortcut)

    def _configure_table(self) -> None:
        """Initialise column headers, font and widths for the table widget."""
        self.table_widget.setColumnCount(len(TABLE_HEADERS))
        self.table_widget.setHorizontalHeaderLabels(TABLE_HEADERS)
        self.table_widget.setFont(QtGui.QFont("Helvetica", 10))
        for column_index, width in enumerate(COLUMN_WIDTHS):
            self.table_widget.setColumnWidth(column_index, width)

    def configure_signals(self) -> None:
        """Wire up table, parameter tree and button signals."""
        vertical_header = self.table_widget.verticalHeader()
        vertical_header.sectionClicked.connect(self.get_plots)
        vertical_header.sectionDoubleClicked.connect(self.get_plots)

        self.params.param("load_classifications").sigActivated.connect(
            self.load_data_to_tbl_widget
        )
        self.params.param("save_triggers").sigActivated.connect(self.save_table_to_csv)

    # ---------------------------------------------------------------- Data loading --
    def load_data_to_tbl_widget(self) -> None:
        """Populate the table widget with predictions from the CSV file."""
        predicted_data = xaap_check.load_csv_file(self)
        if predicted_data is None or predicted_data.empty:
            logger.warning("No predicted data available to populate the table.")
            return

        self.table_widget.clear()
        self._configure_table()

        try:
            display_data = (
                predicted_data[DISPLAY_COLUMNS].fillna("").to_numpy(dtype=object)
            )
        except KeyError as exc:
            logger.error("Missing columns in prediction file: %s", exc)
            return

        self.table_widget.appendData(display_data)
        self._populate_action_widgets()

    def _populate_action_widgets(self) -> None:
        """Insert per-row action widgets (show button and status combo)."""
        for row_index in range(self.table_widget.rowCount()):
            show_button = QPushButton("Show", self.table_widget)
            show_button.setStyleSheet("background-color: blue; color: white")
            show_button.clicked.connect(
                lambda _=False, row=row_index: self.get_plots(row)
            )
            self.table_widget.setCellWidget(row_index, BUTTON_COLUMN_INDEX, show_button)

            status_combobox = QComboBox(self.table_widget)
            status_combobox.addItems(list(STATUS_OPTIONS))
            status_combobox.setCurrentIndex(STATUS_DEFAULT_INDEX)
            self.table_widget.setCellWidget(
                row_index, STATUS_COLUMN_INDEX, status_combobox
            )

    # ----------------------------------------------------------------- Persistence --
    def save_table_to_csv(self) -> None:
        """Export the current table contents, including combo-box values, to CSV."""
        with EXPORT_FILENAME.open("w", newline="") as csv_file:
            writer = csv.writer(csv_file)
            for row in range(self.table_widget.rowCount()):
                row_data: List[str] = []
                for column in range(self.table_widget.columnCount()):
                    cell_widget = self.table_widget.cellWidget(row, column)
                    if isinstance(cell_widget, QPushButton):
                        row_data.append("")
                        continue
                    if isinstance(cell_widget, QComboBox):
                        row_data.append(cell_widget.currentText())
                        continue

                    item = self.table_widget.item(row, column)
                    row_data.append(item.text() if item is not None else "")
                writer.writerow(row_data)

        logger.info("Table exported to %s", EXPORT_FILENAME.resolve())

    # --------------------------------------------------------------------- Plotting --
    def get_plots(self, row: int | None = None) -> None:
        """Plot waveform, padded waveform and spectrogram for the selected row."""
        if row is None:
            row = self.table_widget.currentRow()
        if row < 0:
            logger.warning("No table row selected for plotting.")
            return

        self.table_widget.selectRow(row)
        trigger_item = self.table_widget.item(row, 0)
        if trigger_item is None:
            logger.warning("Row %s does not contain a trigger code.", row)
            return

        trigger_code = trigger_item.text()
        xaap_check.logger.info("Plotting trigger %s from row %s", trigger_code, row)

        (
            self.trigger_times,
            self.paded_stream,
            self.trigger_stream,
            self.paded_times,
            max_trigger,
            min_trigger,
            amp_max,
            max_loc,
            min_loc,
            rms,
        ) = xaap_check.get_trigger(self, trigger_code)

        self._update_table_statistics(row, amp_max, rms)
        self._plot_time_series(max_trigger, min_trigger, max_loc, min_loc)
        self._plot_frequency_information()

    def _update_table_statistics(self, row: int, amp_max: float, rms: float) -> None:
        """Update amplitude and RMS columns with freshly computed values."""
        amp_item = self.table_widget.item(row, 11)
        if amp_item is not None:
            amp_item.setText(str(amp_max))
        rms_item = self.table_widget.item(row, 14)
        if rms_item is not None:
            rms_item.setText(str(rms))

    def _plot_time_series(
        self,
        max_trigger: float,
        min_trigger: float,
        max_loc: int,
        min_loc: int,
    ) -> None:
        """Refresh the time-domain plots for the trigger and padded data."""
        self.trigger_plot.clearPlots()
        self.plot_frequency_spectrum.clearPlots()

        self.trigger_plot.showGrid(x=True, y=True)
        self.trigger_plot.plot(
            [float(self.trigger_times[max_loc])], [max_trigger], symbol="+"
        )
        self.trigger_plot.plot(
            [float(self.trigger_times[min_loc])], [min_trigger], symbol="+"
        )

        self.trigger_stream_procesed = self.trigger_stream.copy()
        self.trigger_stream_procesed[0].detrend("demean")
        self.trigger_stream_procesed[0].filter("highpass", freq=2)
        self.trigger_plot.plot(
            self.trigger_times,
            self.trigger_stream_procesed[0].data,
            pen="g",
        )

        self.paded_plot.clearPlots()
        self.paded_plot.showGrid(x=True, y=True)
        self.paded_plot.plot(self.paded_times, self.paded_stream[0].data, pen="w")
        self.paded_plot.plot(self.trigger_times, self.trigger_stream[0].data, pen="r")

    def _plot_frequency_information(self) -> None:
        """Render FFT and spectrogram plots for the selected trigger."""
        self.plot_frequency_spectrum.showGrid(x=True, y=True)
        frequency_plot = self.plot_frequency_spectrum.plot(
            self.trigger_times, self.trigger_stream[0].data, pen="blue"
        )
        frequency_plot.setFftMode(True)

        self.mw_fig = self.mw.getFigure()
        self.mw_fig.clf()
        self.mw_axes = self.mw_fig.add_subplot(111)

        sampling_rate = self.trigger_stream[0].stats.sampling_rate
        self.trigger_stream.spectrogram(
            wlen=2 * sampling_rate,
            per_lap=0.95,
            dbscale=True,
            log=False,
            axes=self.mw_axes,
            cmap=plt.cm.jet,
        )

        data_duration = len(self.trigger_stream[0].data) / sampling_rate
        wlen = max(data_duration * 0.01, 1)
        nfft = 2 ** np.ceil(np.log2(wlen * sampling_rate))
        logger.debug("Spectrogram configuration: wlen=%s, nfft=%s", wlen, nfft)

        self.trigger_stream.spectrogram(
            wlen=wlen,
            per_lap=0.95,
            dbscale=True,
            log=False,
            axes=self.mw_axes,
            cmap=plt.cm.jet,
        )

        self.mw.draw()

    def clear_all_plots(self) -> None:
        """Remove every plot from the canvas."""
        self.paded_plot.clearPlots()
        self.trigger_plot.clearPlots()
        self.plot_frequency_spectrum.clearPlots()

    # -------------------------------------------------------------- Configuration --
    def create_parameters(self) -> Parameter:
        """Restore GUI parameters from disk or create a new configuration object."""
        xaap_parameters = Parameter.create(
            name="xaap_check_configuration", type="group", children=[]
        )
        xaap_check_json = Path(self.xaap_check_json)
        try:
            if xaap_check_json.exists():
                with xaap_check_json.open("r", encoding="utf-8") as config_file:
                    json_data = json.load(config_file)
                xaap_parameters.restoreState(json_data)
            else:
                logger.error("No configuration file exists: %s", xaap_check_json)
        except Exception as exc:  # pragma: no cover - defensive logging
            logger.error("Error in create_parameters(): %s", exc)

        xaap_check.logger.info("End of set parameters")
        return xaap_parameters


def main() -> None:
    """Entry point used when running the module as a script."""
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--xaap_check_config",
        type=str,
        default="./config/xaap_check.json",
        help="xaap_check_config.cfg to run this module",
    )
    args = parser.parse_args()

    if len(sys.argv) == 1:
        parser.print_help(sys.stderr)

    app = pg.mkQApp()
    app.setStyleSheet(
        """
        QWidget {font-size: 15px}
        QMenu {font-size: 10px}
        QMenu QWidget {font-size: 10px}
        """
    )

    window = xaapCheck(args)
    window.setWindowTitle("xaap_check")
    window.showMaximized()
    window.resize(1100, 700)

    pg.exec()


if __name__ == "__main__":
    print("Configure logging...")
    try:
        configure_logging()
        logger.info("Logging configured successfully.")
    except Exception as exc:  # pragma: no cover - defensive logging
        print(f"Failed to configure logging: {exc}")
        sys.exit(1)

    main()
